vuln_db = {
    20:  "FTP Data - Often supports unencrypted transfer, brute-force attacks",
    21:  "FTP - May allow anonymous login (CVE-1999-0497), weak/no encryption",
    22:  "SSH - Weak passwords, brute-force, outdated encryption",
    23:  "Telnet - Unencrypted, vulnerable to interception, brute-force",
    25:  "SMTP - Open Relay, spam, spoofing (CVE-2000-0284)",
    53:  "DNS - Cache poisoning (CVE-2020-25705), amplification attacks",
    67:  "DHCP (server) - Rogue DHCP, MITM possibilities",
    69:  "TFTP - No authentication, data disclosure (CVE-2002-1561)",
    80:  "HTTP - Unencrypted, XSS, SQL Injection, MITM, HTTP Smuggling",
    110: "POP3 - Credentials in clear text",
    111: "RPCbind - Exposed remote procedure calls (CVE-2017-8779)",
    119: "NNTP - News servers, rarely secured",
    123: "NTP - Amplification, DDoS attacks",
    135: "Microsoft RPC - Used in DCOM, MS08-067 worm vector",
    137: "NetBIOS Name Service - Information leakage, spoofing",
    138: "NetBIOS Datagram Service - Information exposure",
    139: "NetBIOS Session Service - SMB relay, worm propagation",
    143: "IMAP - Credentials in clear text, exploitable mail servers",
    161: "SNMP - Public/private defaults, data exposure (CVE-2017-6736)",
    162: "SNMP Trap - Can be used for attacks if misconfigured",
    389: "LDAP - Info disclosure, weak authentication (CVE-2017-8563)",
    443: "HTTPS - Outdated SSL/TLS, Heartbleed (CVE-2014-0160)",
    445: "SMB - EternalBlue (CVE-2017-0144), WannaCry, ransomware spread",
    465: "SMTPS - Weak SSL ciphers possible",
    512: "rexec - No encryption, command execution",
    513: "rlogin - No encryption, MITM and credential theft",
    514: "syslog/rsh - Cleartext, info disclosure, command execution",
    554: "RTSP - Buffer overflows, weak auth, used in DVR exploits",
    587: "SMTP Submission - Email spoofing if misconfigured",
    631: "IPP (Internet Printing) - PrintNightmare, CVE-2021-34527",
    993: "IMAPS - SSL/TLS issues possible, default SSL ciphers",
    995: "POP3S - SSL vulnerabilities, outdated ciphers",
    1024: "Reserved/ephemeral - Rare but historically vulnerable",
    1433: "MSSQL - Weak auth, brute-force, SQL injection (CVE-2012-2122)",
    1434: "MSSQL Monitor - Slammer Worm, buffer overflow (CVE-2002-0649)",
    1723: "PPTP VPN - Weak MS-CHAPv2, interception",
    2049: "NFS - Unauthenticated file sharing (CVE-1999-1376)",
    2082: "cPanel (non-SSL) - Web attacks if unpatched",
    2083: "cPanel (SSL) - SSL issues, web exploitation",
    3306: "MySQL - Default root account, brute-force, code execution (CVE-2012-2122)",
    3389: "RDP - BlueKeep (CVE-2019-0708), brute-force, ransomware",
    5432: "PostgreSQL - Weak configuration, default accounts",
    5900: "VNC - Unencrypted, weak passwords",
    8080: "HTTP-Alt - Proxies, XSS, web attacks, SSRF",
    8443: "HTTPS-Alt - Web exploits, SSL issues, outdated certificate handling",
    8888: "Alternate HTTP - Same as 8080, unpatched web apps"
}
